# Generated by Django 3.2.3 on 2022-12-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField(max_length=10, null=True)),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.CharField(max_length=255)),
                ('Archived', models.BooleanField(default=False)),
                ('DateOfCreate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
