# Generated by Django 3.2.3 on 2022-12-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfCreated', models.DateField(auto_created=True)),
                ('CustName', models.CharField(max_length=20)),
                ('CustNo', models.CharField(max_length=20)),
                ('OrgnizationName', models.CharField(max_length=50)),
                ('Gender', models.CharField(default='M', max_length=2)),
                ('CustPhone', models.CharField(blank=True, default='', max_length=50)),
                ('CustEmail', models.EmailField(blank=True, default='', max_length=100)),
                ('CustAddr', models.CharField(blank=True, default='', max_length=255)),
                ('Hat', models.CharField(blank=True, default='', max_length=10)),
                ('shoulder_width', models.CharField(blank=True, default='', max_length=10)),
                ('sleeve_length', models.CharField(blank=True, default='', max_length=10)),
                ('back_length', models.CharField(blank=True, default='', max_length=10)),
                ('center_back', models.CharField(blank=True, default='', max_length=10)),
                ('shirt_length', models.CharField(blank=True, default='', max_length=10)),
                ('collar', models.CharField(blank=True, default='', max_length=10)),
                ('chest', models.CharField(blank=True, default='', max_length=10)),
                ('waist', models.CharField(blank=True, default='', max_length=10)),
                ('seat', models.CharField(blank=True, default='', max_length=10)),
                ('waist_belt', models.CharField(blank=True, default='', max_length=10)),
                ('hip', models.CharField(blank=True, default='', max_length=10)),
                ('crotch', models.CharField(blank=True, default='', max_length=10)),
                ('front_crotch', models.CharField(blank=True, default='', max_length=10)),
                ('thigh', models.CharField(blank=True, default='', max_length=10)),
                ('pants_length', models.CharField(blank=True, default='', max_length=10)),
                ('skirt_length', models.CharField(blank=True, default='', max_length=10)),
                ('remark', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
