# Generated by Django 3.2.3 on 2022-12-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hf_uniform_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='OrgnizationName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
