# Generated by Django 3.2.3 on 2022-12-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hf_uniform_app', '0003_auto_20221206_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniform',
            old_name='Back_length',
            new_name='BackLength',
        ),
        migrations.RenameField(
            model_name='uniform',
            old_name='Center_back',
            new_name='CenterBack',
        ),
        migrations.RenameField(
            model_name='uniform',
            old_name='Front_crotch',
            new_name='FrontCrotch',
        ),
        migrations.RenameField(
            model_name='uniform',
            old_name='Pants_length',
            new_name='PantsLength',
        ),
        migrations.RenameField(
            model_name='uniform',
            old_name='Shirt_length',
            new_name='ShirtLength',
        ),
        migrations.RenameField(
            model_name='uniform',
            old_name='Shoulder_width',
            new_name='ShoulderWidth',
        ),
        migrations.RenameField(
            model_name='uniform',
            old_name='Skirt_length',
            new_name='SkirtLength',
        ),
        migrations.RenameField(
            model_name='uniform',
            old_name='Sleeve_length',
            new_name='SleeveLength',
        ),
        migrations.RenameField(
            model_name='uniform',
            old_name='Waist_belt',
            new_name='WaistBelt',
        ),
    ]
