# Generated by Django 3.2.3 on 2022-12-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hf_uniform_app', '0004_auto_20221208_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='DateOfCreated',
            field=models.DateField(),
        ),
    ]
