# Generated by Django 3.2.3 on 2022-12-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hf_uniform_app', '0005_alter_uniform_dateofcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='CustNo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
