# Generated by Django 3.2.3 on 2022-12-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('taskContent', models.CharField(max_length=250)),
                ('complete', models.BooleanField(default=False)),
                ('dateOfCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
